### ISSUE TITLE
Some photos are not recognized as .HEIC files

### ISSUE THREAD

**Issue by zigm** [MrGee53/HeicToJpg#1]
Tried steps described under Using the Windows 10 release". HeicToJpg.exe reports "IMG_1259.heic is not .HEIC... Skipping".
The same HEIC File is dispayed properly under gmail.

**Comment by MrGee53** [comment]
I was having the same problem with some of my photos. I don't know what causes it yet, but I'll start working on a fix.

**Comment by MrGee53** [comment]
I found what was causing the bug. If the file extension was ".heic" instead of ".HEIC" it would skip over it. The new release is now up under [HeicToJpg v0.1.1](https://github.com/MrGee53/HeicToJpg/releases/tag/v0.1.1)

**Comment by zigm** [comment]
Thnak you much. It works now.
Zbigniew
